version: '3'

services:
    mongodb1:
        image: mongo
        container_name: mongodb1
        volumes:
        - ./out/mongodata1:/data/db
        expose:
        - "27017"
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]

    mongodb2:
        image: mongo
        container_name: mongodb2
        volumes:
        - ./out/mongodata2:/data/db
        expose:
        - "27017"
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]
      
            
    mongodb3:
        image: mongo
        container_name: mongodb3
        volumes:
        - ./out/mongodata3:/data/db
        expose:
        - "27017"
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all" ]

    mongoArbite:
        image: mongo
        container_name: mongoArbite
        volumes:
        - ./out/mongoArbite:/data/db
        expose:
        - "27017"
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all" ]